server:
  port: 9001
  tomcat:
    keep-alive-timeout: 15s
    connection-timeout: 2s    # default is 20s
    threads:
      max: 50 # default is 200
      min-spare: 5 # default is 10

polar:
  greeting: Welcome to the local book catalog!
  test: true

spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: true
      retry: # fail-fast 要設為true才會生效
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/polardb_catalog
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
management:
  endpoints:
    web:
      exposure:
        include:
          - refresh